### ISSUE TITLE
i cant extract firmwares

### ISSUE THREAD

**Issue by cyanidecup** [Ciastex/SagemFirmwareExtractor#1]
i cant extract the firmwares that i downloaded, what file format do they have to be in?

**Comment by Ciastex** [comment]
Right now, extraction directly from firmware installer is not supported. You need to extract the actual firmware yourself, because the entire thing is first compressed using NSIS, and then the extracted firmware installer has the firmware binary in its resource table. Using Resource Hacker or PE Explorer extract the firmware from PBCS resource section of the executable. Below is a picture describing example of what you're looking for. Save that resource as raw binary, then point the extractor to it.

![screen](https://img.vddcore.eu/70hSKm-6.png)

**Comment by cyanidecup** [comment]
thanks, can you add support for other file formats? such as .aac .mp3 .imy and other?

**Comment by Ciastex** [comment]
Check it out now. It should recognize most of the multimedia files in the firmwares. It also supports extraction from the 2nd-level .exe (the one extracted from temporary directory) - just use `SagemExtract fileName.exe --extract-exe` and it should work. For manually extracted firmwares use it as you would normally.

**Comment by cyanidecup** [comment]
wow, amazing! do you have a discord, we could talk about these old phone firmwares

**Comment by cyanidecup** [comment]
also for tomorrow, can you add support for .dls files (i heard they are used for the phones software sound chip)

**Comment by cyanidecup** [comment]
hey man can you make a simillar extractor for alcatel phones? most models like ot-757/ot-535 have amr files but idk the file system
